# Copyright 2020 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: video-generator-lock
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard-rwx
  resources:
    requests:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-generator
  namespace: default
  labels:
    app: video-generator
spec:
  replicas: $VIDEO_GENERATOR_REPLICAS
  selector:
    matchLabels:
      app: "video-generator"
  template:
    metadata:
      labels:
        app: video-generator
    spec:
      volumes:
      - name: sheet-lock
        persistentVolumeClaim:
          claimName: video-generator-lock
      containers:
      - name: video-generator
        image: $IMAGE_NAME
        volumeMounts:
        - name: sheet-lock
          mountPath: /sheet_lock
        env:
        - name: SPREADSHEET_ID
          value: $SPREADSHEET_ID
        - name: GCS_BUCKET_NAME
          value: $GCS_BUCKET_NAME
        - name: GCP_PROJECT_NUMBER
          value: "$GCP_PROJECT_NUMBER"
        - name: SHEET_LOCK_FILE
          value: "/sheet_lock/lock_file"
        - name: DISABLE_SHEET_LOGGING
          value: "$DISABLE_SHEET_LOGGING"
